In [1]:
import numpy as np

In [3]:
one_d_array = np.array([1, 2, 3, 4, 5, 6])
print(one_d_array)

[1 2 3 4 5 6]


In [4]:
two_d_array = np.array([[1, 2], [3, 4]])
print(two_d_array)

[[1 2]
 [3 4]]


In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
sequence_of_int = np.arange(5, 12)

In [8]:
print(sequence_of_int)

[ 5  6  7  8  9 10 11]


In [10]:
rand_int_btwn_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(rand_int_btwn_50_and_100)

[54 58 53 61 79 80]


In [11]:
random_floats = np.random.random([6])

In [12]:
print(random_floats)

[0.3355586  0.53420625 0.0250748  0.6603029  0.45678009 0.09803956]


In [13]:
random_floats_btwn_2_and_3 = random_floats + 2.0
print(random_floats_btwn_2_and_3)

[2.3355586  2.53420625 2.0250748  2.6603029  2.45678009 2.09803956]


In [14]:
random_integers_between_150_and_300 = rand_int_btwn_50_and_100 * 3
print(random_integers_between_150_and_300)

[162 174 159 183 237 240]


Task 1: Create a linear dataset     

In [15]:
feature = np.arange(6, 21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [18]:
label = 3 * feature + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


Add some noise to dataset

In [20]:
noise = np.random.randint(low=-2, high=2, size=(len(label)))
print(noise)

[-1 -2 -1  0 -1  0  0  1 -2 -2  0 -1  0 -2  1]


In [21]:
noisy_label = label + noise
print(noisy_label)

[21 23 27 31 33 37 40 44 44 47 52 54 58 59 65]
